apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  annotations:
    openshift.io/display-name: fraud
    serving.kserve.io/deploymentMode: ModelMesh
  labels:
    name: fraud
    opendatahub.io/dashboard: "true"
  name: fraud
spec:
  predictor:
    model:
      modelFormat:
        name: onnx
        version: "1"
      runtime: triton
      storage:
        key: aws-connection-minio
        path: fraud/
