---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  component: rhods

namespace: redhat-ods-operator

resources:
- namespace.yml
- operatorgroup.yml
- subscription.yml
